# Generated by Django 2.2 on 2019-04-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=100)),
                ('Specialist_in', models.CharField(max_length=50)),
                ('Hospital_Name', models.CharField(max_length=100)),
                ('Available_Days', models.CharField(max_length=100)),
                ('Timings', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=10)),
                ('timing', models.CharField(max_length=10)),
                ('problem', models.CharField(max_length=150)),
                ('symptoms', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
